// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzspanlainyszrvitzzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56c3BhbmxhaW55c3pydml0enpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NjMyNTQsImV4cCI6MjA2MTQzOTI1NH0.LmOmo2Oz0GyLA6MZs0fzaUFaVhZ0rdZsyPLYF2LNQOs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);